### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by bangnokia**
I fix some typos cause warning about violation psr-4 when install with composer.

### CODE REVIEW

**Comment by itsjeffro** [comment]
Approved. Thanks for contributing, @bangnokia

**Comment by itsjeffro** [comment]
@bangnokia Can you point it at branch 1.x

**Comment by bangnokia** [comment]
@itsjeffro thank you, i updated. but i don't know am i doing correctly or not.

**Comment by itsjeffro** [comment]
Hi @bangnokia

My mistake, I though this would have been a hotfix for the 1.x branch.

Since this contains changes from master, can you point it at master again. Master contains updates for version 2.

Then I'll approve and merge it.

Thanks

**Comment by bangnokia** [comment]
@itsjeffro yep, i updated

**Pull request merged**
